### ISSUE TITLE
transform pattern

### ISSUE THREAD

**Issue by llllllllll** [llllllllll/codetransformer#10]
I would like to start thinking about the API for the transformers to allow for pattern matching.

Some ideas:
### `multipledispatch`

The idea with using multiple dispatch would be to attempt to call some dispatched function over all of the instructions, shrinking the tuple until we get a match, and then consuming all of the instructions and continuing.
#### pros
1. existing, well tested library
2. I know how to use it from blaze
3. clear syntax with the decorator patterm
#### cons
1. greedy matching
2. no blog or abstract pattern stuff
### custom pattern DSL

We can always just write some pattern language and mix the abstract pattern types in with our concrete instruction types like:

``` python

@dispatch(SETUP_WITH, var, WITH_CLEANUP_FINISH)
def visit_pattern(self, *instrs):
    ....
```
#### pros
1. more expressive
#### cons
1. a lot more work
### use quasiquotes to have a lexer generator block inlined

We could always go full crazy and do something like alex in our code to define this stuff:

example:

``` python
class MyTransformer(CodeTransformer):
    with $rules:
        SETUP_WITH .* WITH_CLEANUP_FINISH { visit_with }
        STORE_FAST LOAD_FAST              { visit_roundtrip }

    def visit_with(self, *instrs):
        ...

    def visit_roundtrip(self, store, load):
        ...
```
#### pros
1. This is wild
2. really cool
3. I want to do this
4. super readable (when you know what you are seeing)
5. regex-like
6. frees us from the grip of valid python syntax
#### cons
1. quasiquotes are not really that well supported
2. a **lot** more work
3. potentially harder for people to understand

**Comment by ssanderson** [comment]
I think it will be easier to think about this with some particular use-cases in mind.

Thinking about our dict/set/list comprehension bug, the issue there is that you need to be able to operate on a section of code of the form `BUILD_LIST 0, ... LIST_APPEND JUMP_ABSOLUTE`.  You essentially want to be able to replace this block of instructions with a different block.  Some sort of regex-inspired matching API seems reasonable here.

Our attempts at warp-speed inline-reduce/compose are trickier.  There, you want to be able to take the bytecode of existing functions, and concatenate them together in an intelligent way with modifications.  Do we expect the API discussed here to support this kind of operation, or is that a separate issue?

Are there other use-cases you can think of for the pattern-matching case.  You mentioned that @jcrist was interested in using us somewhere in dask?

**Comment by llllllllll** [comment]
I have the inline reduce working already, very cleanly. I will send it to you. The dask case would look almost exactly like lazy_function
