### ISSUE TITLE
`asconstants` doesn't visit LOAD_DEREF, LOAD_FAST, or LOAD_CLASSDEREF instructions

### ISSUE THREAD

**Issue by ssanderson** [llllllllll/codetransformer#20]
It should almost certainly be visiting LOAD_DEREF.  The others are less clear.  LOAD_CLASSDEREF should only appear in the body of a class, which I don't think we know how to visit?  And LOAD_FAST implies that there's a local store to the name somewhere in the function.  We might also want to be more explicit about rejecting any STORE_\* instructions to a name that's been declared frozen.

**Comment by llllllllll** [comment]
merged
