### ISSUE TITLE
Possible support for simple inline code modifications. 

### ISSUE THREAD

**Issue by Erotemic** [llllllllll/codetransformer#63]
This morning I had a shower idea: "Python function calls can have a high overhead. What if we could use the disassembler to directly insert a function's bytecode into the bytecode of the caller function?". 

I wrote a mwe to show that this might provide some speed benefit on some cases:

```python
def add(a, b):
    return a + b


def mult(c, d):
    """
    Time calling the add function and its internal bytecode
    """
    result = 0
    for _ in range(d):
        a = result
        b = c
        result = add(a, b)
    return result

def mult_inline(c, d):
    """
    Time calling just the bytecode inside the add function
    """
    result = 0
    for _ in range(d):
        a = result
        b = c
        result = a + b
    return result

def baseline(c, d):
    """
    Overhead of the function without calling add at all
    """
    result = 0
    for _ in range(d):
        a = result
        b = c
        pass
    return result

def mwe():
    c, d = 100, 100
    import ubelt as ub
    mt = ub.Timerit(100, label='mult')
    for timer in mt:
        with timer: mult(c, d)

    mit = ub.Timerit(100, label='mult-inline')
    for timer in mit:
        with timer: mult_inline(c, d)

    bt = ub.Timerit(100, label='baseline')
    for timer in bt:
        with timer: baseline(c, d)

    overhead = min(bt.times)
    nocall = min(mit.times)
    withcall = min(mt.times)

    # time of a single call to the interesting parts
    add_time = (nocall - overhead) / d * 1e9
    call_add_time = (withcall - overhead) / d * 1e9
    call_time = call_add_time - add_time
    print('add_time = {:.2f} ns'.format(add_time))
    print('call_add_time = {:.2f} ns'.format(call_add_time))
    print('call_time = {:.2f} ns'.format(call_time))

if __name__ == '__main__':  
    mwe()
```
Output:
```
Timing complete for: mult, 100 loops, best of 3
    time per loop : best=12.1 µs, ave=12.14 ± 0.15 µs
Timing complete for: mult-inline, 100 loops, best of 3
    time per loop : best=5.731 µs, ave=5.881 ± 0.35 µs
Timing complete for: baseline, 100 loops, best of 3
    time per loop : best=2.547 µs, ave=4.608 ± 3.3 µs
add_time = 31.84 ns
call_add_time = 95.52 ns
call_time = 63.68 ns
```

This analysis shows that the overhead for calling a function is about 63 nanoseconds in this case. When we insert the bytecode inline inside the loop, we end up saving ~2.5 microseconds. 

This shows that there may be some benefit to doing this in simple cases. In more complex cases, this may not be feasible due to the semantics of function scopes, but in simple cases (i.e. where the args to a callee are not modified, and other assumptions I haven't thought of yet are met), this might be doable. 

While thinking about this I recalled the PyCon 2016 talk and I rewatched it, and was reminded that the `codetransformer` project exists. I skimmed the code, but didn't see anything that explicitly did what I envisioned. I was wondering if a PSF certified bytecode expert might weigh in on whether or not this seemed feasible / interesting. 

From my initial reading / experiments, there are a few challenges/side-effects that need to be addressed/accepted to do something like this: 

* the locals need to be expanded to include the variables from the inlined function
* need to resolve conflicts between variable names
* return statements need to be resolved to assignments to variables in the caller
* multiple return statements will not work (return outside function)
* closures, nonlocal, and global access seem like a pain but perhaps could be ignored on a first pass
* code that reassigns the values of its argument variables may produce unintended results. 
* doing this will trash any hope of getting a reasonable traceback, but that's probably ok.

Might something like this be easy to do with `codetransformer`? Any ideas for where to get started / things that may cause issues that I haven't considered?

**Comment by ssanderson** [comment]
You might be interested in [gotenks](https://github.com/llllllllll/gotenks), which is @llllllllll's experimental library for doing [stream fusion](https://eva.fing.edu.uy/pluginfile.php/177169/mod_resource/content/1/StreamFusion.pdf) on python iterators.  Part of that implementation includes an [InlineTransformer](https://github.com/llllllllll/gotenks/blob/7db597fa2ae968a18a883108a8e7c100a16475cd/gotenks/compose.py#L26), which sounds similar to what you're describing.

**Comment by Erotemic** [comment]
Thanks for the pointer! That's exactly the sort of thing I was hoping to discover by asking this question.
