### ISSUE TITLE
Code object documentation says to_bytecode() not to_pycode()

### ISSUE THREAD

**Issue by pganssle** [llllllllll/codetransformer#64]
I'm guessing it's an old version of the API, but [the documentation](https://codetransformer.readthedocs.io/en/stable/code-objects.html) says:

> We can convert our Code object back into its raw form via the `to_bytecode()` method:

Presumably it should say "via the `to_pycode()` method:"

**Comment by llllllllll** [comment]
fixed in https://github.com/llllllllll/codetransformer/commit/c5f551e915df45adc7da7e0b1b635f0cc6a1bb27

Thanks for reporting this!
