### ISSUE TITLE
overridden literals functions are broken for comprehensions

### ISSUE THREAD

**Issue by ssanderson** [llllllllll/codetransformer#8]
dict/list/set comprehensions use `BUILD_{type} 0` plus an iterator and a sequence of `MAP_ADD`/`LIST_APPEND`/`SET_ADD` instructions, which breaks with the current transformers that assume you can just insert a function call after BUILD_\* call.

The right fix for this is probably a more expressive pattern-based API.

**Comment by llllllllll** [comment]
pr pls
